### ISSUE TITLE
pystac-client request with intersects fails against resto

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#329]
**Describe the bug**
pystac_client seems to have an issue when submitting a geometry to a resto /search endpoint

**To Reproduce**

```python
from pystac_client import Client
client = Client.open("https://tamn.snapplanet.io")
collection = "S2"
geometry = '{"type": "Polygon", "coordinates": [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]]]}'
search = client.search(method="GET", collections=[collection], intersects=geometry)
print(len(list(search.items_as_dicts())))
```

Exception is thrown:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    print(len(list(search.items_as_dicts())))
  File "/Users/philvarner/code/stac-api-validator/.venv/lib/python3.10/site-packages/pystac_client/item_search.py", line 682, in items_as_dicts
    for page in self._stac_io.get_pages(
  File "/Users/philvarner/code/stac-api-validator/.venv/lib/python3.10/site-packages/pystac_client/stac_api_io.py", line 220, in get_pages
    page = self.read_json(url, method=method, parameters=parameters)
  File "/Users/philvarner/code/stac-api-validator/.venv/lib/python3.10/site-packages/pystac/stac_io.py", line 198, in read_json
    txt = self.read_text(source, *args, **kwargs)
  File "/Users/philvarner/code/stac-api-validator/.venv/lib/python3.10/site-packages/pystac_client/stac_api_io.py", line 97, in read_text
    return self.request(href, *args, **kwargs)
  File "/Users/philvarner/code/stac-api-validator/.venv/lib/python3.10/site-packages/pystac_client/stac_api_io.py", line 144, in request
    raise APIError.from_response(resp)
pystac_client.exceptions.APIError: {"ErrorMessage":"search - pQuery - ","ErrorCode":400}
```

Filing this against resto instead of pystac-client as I know this works with other STAC APIs, but it could be an issue with pystac-client.

**Expected behavior**

The results are paged over and the total count is printed.

**Comment by jjrom** [comment]
Thanks @philvarner for raising this issue. Apparently pystac_client sends intersects property with trailing double quotes i.e. :

`intersects = "\"{\\\"type\\\": \\\"Polygon\\\", \\\"coordinates\\\": [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]]]}\""` 

It looks like a double encoding of the string which is not valid imho and probably an issue in pystac_client

Anyway I had a test in resto within the query processing to handle this case and update tamn.snapplanet.io accordingly so you can test it without error now

**Comment by jjrom** [comment]
Report an issue on [pystac_client](https://github.com/stac-utils/pystac-client/issues/335l)

**Comment by philvarner** [comment]
I think throwing a 400 error here is appropriate, since it's not a valid geometry.

**Comment by jjrom** [comment]
I will update resto to throw a 400 error on input invalid geometry once pystac_client issue is corrected.
